version: '3'

networks:
  firefly_lan:
    external: true
  proxynet:
    external: true

volumes:
  upload:
  db:

services:
  app:
    image: fireflyiii/core:version-5.7.9
    container_name: firefly
    hostname: firefly
    restart: 'unless-stopped'
    volumes:
      - upload:/var/www/html/storage/upload
    networks:
      - firefly_lan
      - proxynet
    env_file: .env
    expose:
      - 8080
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxynet'
      - 'traefik.http.routers.firefly.rule=Host(`${HOSTNAME}`)'
      - 'traefik.http.routers.firefly.entrypoints=websecure'
      - 'traefik.http.routers.firefly.tls=true'
      - 'traefik.http.services.firefly.loadbalancer.server.port=8080'
  db:
    image: mariadb:10.8
    container_name: fireflydb
    hostname: fireflydb
    restart: 'unless-stopped'
    env_file: .db.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - firefly_lan
